version: 2
builds:
  - id: main
    main: ./cmd/vip
    binary: vip
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/nentgroup/viaplay-cli/internal/cli.Version={{.Version}}
      - -X github.com/nentgroup/viaplay-cli/internal/cli.BuildDate={{.Date}}
      - -X github.com/nentgroup/viaplay-cli/internal/cli.Commit={{.Commit}}
      - -X github.com/nentgroup/viaplay-cli/internal/gh.defaultClientID={{.Env.CLIENT_ID}}
archives:
  -
    format_overrides:
      - goos: windows
        formats: ['zip']
homebrew_casks:
  -
    name: vip
    caveats: "If you have an existing binary at /opt/homebrew/bin/vip, remove it before installing: rm /opt/homebrew/bin/vip"
    binary: vip
    uninstall:
      delete:
        - "/opt/homebrew/bin/vip"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vip"]
          end
    repository:
      owner: nentgroup
      name: viaplay-cli
    commit_author:
      name: Alessandro Coletti
      email: alessandro.coletti@viaplaygroup.com
    directory: Casks
    homepage: "https://nentgroup.github.io/viaplay-cli"
    description: "CLI tool for Gecko Generators."
    url:
      template: "https://github.com/nentgroup/viaplay-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      using: "GitHubPrivateRepositoryReleaseDownloadStrategy"
    custom_block: |
      require File.expand_path("lib/custom_download_strategy.rb", __dir__)
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'