version: 2
project_name: vip
builds:
  - id: main
    main: ./cmd/vip
    binary: vip
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/nentgroup/viaplay-cli/internal/cli.Version={{.Version}}
      - -X github.com/nentgroup/viaplay-cli/internal/cli.BuildDate={{.Date}}
      - -X github.com/nentgroup/viaplay-cli/internal/cli.Commit={{.Commit}}
      - -X github.com/nentgroup/viaplay-cli/internal/gh.defaultClientID={{.Env.CLIENT_ID}}
archives:
  - id: vip
    ids:
      - main
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: ['zip']

nfpms:
  - package_name: vip
    id: vip-linux
    ids:
      - main
    formats:
      - apk
      - deb
      - rpm
    vendor: nentgroup
    homepage: https://nentgroup.github.io/viaplay-cli
    maintainer: Alessandro Coletti <alessandro.coletti@viaplaygroup.com>
    description: "vip is a CLI for scaffolding projects, creating GitHub repos, and applying team standards."
    license: MIT
    section: utils
    priority: optional
    bindir: /usr/local/bin
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Arch }}

winget:
  - publisher: nentgroup
    package_identifier: nentgroup.vip
    short_description: "vip is a CLI for scaffolding projects and GitHub automation"
    license: MIT
    homepage: https://nentgroup.github.io/viaplay-cli
    repository:
      owner: nentgroup
      name: viaplay-cli
      branch: main

homebrew_casks:
  - name: vip
    caveats: "If you have an existing binary at /opt/homebrew/bin/vip, remove it before installing: rm /opt/homebrew/bin/vip"
    binary: vip
    uninstall:
      delete:
        - "/opt/homebrew/bin/vip"
    hooks:
      post:
        install: |
          if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vip"]
          end
    repository:
      owner: nentgroup
      name: viaplay-cli
    commit_author:
      name: Alessandro Coletti
      email: alessandro.coletti@viaplaygroup.com
    directory: Casks
    homepage: "https://nentgroup.github.io/viaplay-cli"
    description: "CLI tool for scaffolding projects and GitHub automation."
    url:
      template: "https://github.com/nentgroup/viaplay-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'