# This file was generated by GoReleaser. DO NOT EDIT.
cask "vip" do
  tap_path = File.expand_path("Library/Taps/nentgroup/homebrew-viaplay-cli/Casks/lib/custom_download_strategy.rb", ENV["HOMEBREW_PREFIX"])
  require tap_path

  name "vip"
  desc "CLI tool for Gecko Generators."
  homepage "https://nentgroup.github.io/viaplay-cli"
  version "2.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vip"

  on_macos do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v#{version}/viaplay-cli_#{version}_darwin_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "23d2c5695f3356fd56c977b858328f7d3f8eb891e566bea994f178faaaf28332"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v#{version}/viaplay-cli_#{version}_darwin_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "09c3647cdeec5313cc52f2dfde2cad00422e1d4110ef9cb494d8a40162ac02c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v#{version}/viaplay-cli_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e5a9e7082692b0d33bc242a3d43e475f4480dd85c1642b35d494e25344e10b1e"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v#{version}/viaplay-cli_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "17792f83e860bd85e95649531d307371cb8f66102fdab09b7cd8b016719e0e05"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vip"]
    end
  end

  caveats do
    "If you have an existing binary at /opt/homebrew/bin/vip, remove it before installing: rm /opt/homebrew/bin/vip"
  end

  uninstall delete: [
      "/opt/homebrew/bin/vip",
    ]

  # No zap stanza required
end
