# This file was generated by GoReleaser. DO NOT EDIT.
cask "vip" do
  require File.expand_path("lib/custom_download_strategy.rb", __dir__)

  desc "CLI tool for Gecko Generators."
  homepage "https://nentgroup.github.io/viaplay-cli"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vip"

  on_macos do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.0.0/viaplay-cli_1.0.0_darwin_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "61a51cd07d74cad5614eb5074bc7f6361f059082bad2c91299d30059a3be10b2"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.0.0/viaplay-cli_1.0.0_darwin_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "18aa906c12add44512ed52d877ece1edfe0f43a93c895dbbefe28dff16d3a5c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.0.0/viaplay-cli_1.0.0_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "77d5491adbbc940dd0713ce0d8022163d67ddf14c31907ca58f4617c6d928407"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.0.0/viaplay-cli_1.0.0_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "29dcc149122e282e848537ac114fa8c8ca4ed7e93a5b0a292620b255d2c5e67b"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vip"]
    end
  end

  caveats do
    "If you have an existing binary at /opt/homebrew/bin/vip, remove it before installing: rm /opt/homebrew/bin/vip"
  end

  uninstall delete: [
      "/opt/homebrew/bin/vip",
    ]

  # No zap stanza required
end
