# This file was generated by GoReleaser. DO NOT EDIT.
cask "vip" do
  require File.expand_path("lib/custom_download_strategy.rb", __dir__)

  desc "CLI tool for Gecko Generators."
  homepage "https://nentgroup.github.io/viaplay-cli"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vip"

  on_macos do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.3.0/viaplay-cli_1.3.0_darwin_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "757c741d4713c448066bbf8af069abcb43751d5f4b0022bfb563a38cc08f73a7"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.3.0/viaplay-cli_1.3.0_darwin_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f61e280e05d5aaf67fc69e3ac6a2c3cd8f51faf8899323841991f27fa5111764"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.3.0/viaplay-cli_1.3.0_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "eb231508ee970d3b641bdeb6b541e8f60bba3b859b67ece070b641ec6ec1252c"
    end
    on_arm do
      url "https://github.com/nentgroup/viaplay-cli/releases/download/v1.3.0/viaplay-cli_1.3.0_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "81d3edade5888fce1e1e9f06db9fb4b9de465bc2c1c3283dedee56083a286c6a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vip"]
    end
  end

  caveats do
    "If you have an existing binary at /opt/homebrew/bin/vip, remove it before installing: rm /opt/homebrew/bin/vip"
  end

  uninstall delete: [
      "/opt/homebrew/bin/vip",
    ]

  # No zap stanza required
end
