// Code generated by gatewaygen; DO NOT EDIT.

// Package name is set dynamically by the generator.
package gatewayregister

import (
	"context"
	"log"
	"github.com/nentgroup/viasport-catalog-client-go/v2/catalog"
)

var client = catalog.New()

func RegisterService(ctx context.Context) {
	req := catalog.RegisterRequest{
		Name:       "",
		Target:     "",
		ListenPath: "",
		StripPath:  false,
		Endpoints: []catalog.Endpoint{
			
		},
	}
	if _, err := client.Register(ctx, req); err != nil {
		log.Printf("Failed to register service: %v", err)
	}
}

func DeRegisterService(ctx context.Context) {
	if err := client.DeRegister(ctx, ""); err != nil {
		log.Printf("Failed to unregister service: %v", err)
	}
}
