# GitHub Secrets Configuration
# This file defines secrets to be applied to GitHub repositories
# See https://docs.github.com/en/actions/security-guides/encrypted-secrets
# for viaplay-cli documentation on secrets see http://nentgroup.github.io/viaplay-cli/#/secrets

secrets:
  - name: AWS_BADGES_BUCKET_NAME
    value: "${{secrets.AWS_BADGES_BUCKET_NAME}}"
    type: secret

  - name: AWS_BADGES_BUCKET_KEY
    value: "${{secrets.AWS_BADGES_BUCKET_KEY}}"
    type: secret

  - name: AWS_BADGES_BUCKET_SECRET
    value: "${{secrets.AWS_BADGES_BUCKET_SECRET}}"
    type: secret

  # this secret would be applied on the stage environment
  #- name: STAGE_AWS_BADGES_BUCKET_NAME
  #  value: "${{secrets.STAGE_AWS_BADGES_BUCKET_NAME}}"
  #  type: secret | variable
  #  env: stage

  # this secret would be applied on repository level
  #- name: AWS_BADGES_BUCKET_SECRET
  #  value: "${{secrets.AWS_BADGES_BUCKET_SECRET}}"
  #  type: secret | variable